services:
  backend:
    build:
      context: ./BE
      dockerfile: backend.Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./BE:/code
    depends_on:
      - redis
      - postgres
    env_file:
      - ./BE/.env
    networks:
      - app-network
  
  frontend:
    build: 
      context: ./FE
      dockerfile: frontend.Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./FE/.env.development
    networks:
      - app-network

  celery-worker:
    build:
      context: ./BE
      dockerfile: backend.Dockerfile
    container_name: celery-worker
    command: celery -A app.core.celery.celery_app worker --loglevel=info
    env_file:
      - ./BE/.env
    volumes:
      - ./BE:/code    
    depends_on:
      - backend
      - redis
      - postgres
    networks:
    - app-network

  alembic:
    build:
      context: ./BE
      dockerfile: backend.Dockerfile
    container_name: alembic-migration
    command: alembic upgrade head
    volumes:
      - ./BE:/code
    depends_on:
      - postgres
      - redis
    env_file:
      - ./BE/.env
    networks:
      - app-network
    restart: "no"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data
    networks: 
      - app-network
  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
 app-network:

volumes:
  postgres_data:
  redis_data: